### ISSUE TITLE
Is theme removed?

### ISSUE THREAD

**Issue by azzamsa** [nschloe/github-trends#108]
Hi.

I know this repo from [Zeno Rocha on Twitter: "Dracula has surpassed Solarized in terms of GitHub stars. Thank \*you\* for making it the most popular theme on GitHub! 🧛‍♂️ https://t.co/SJKJQOCoyg 📊 Graph by @nschloe https://t.co/YUg6pKot62" / Twitter](https://twitter.com/zenorocha/status/1386677471513223172).

It theme comparison removed?

**Comment by nschloe** [comment]
It's right here: https://github.com/nschloe/github-trends#color-schemes

**Comment by azzamsa** [comment]
Oh, I was searching for `theme` 

Huge thanks for the graph! :tada:
